export const STATUS = [
  '',
  'Tạo mới',
  'Chờ duyệt',
  'Đã duyệt',
  'Đóng gói',
  'Giao hàng',
  'Nhận hàng',
  'Hủy']
export const INTERNAL_STATUS = [
  '',
  'Đã đặt',
  'Không được nợ',
  'Được nợ',
  'Đã thanh toán',
  'Cần quyền hạn cao hơn',
  'Đơn hàng bị hủy',
  'Đồng ý cho nợ quá hạn mức',
  'Đã duyệt đơn hàng',
  'Đã đồng ý xuất hàng',
  'Đang giao',
  'Đã giao',
  'Thành công',
  'Đóng gói',
]
